version: '3'

services:
  engine-compiler:
    image: maven:3.5.2-jdk-8-alpine
    container_name: engine-compiler
    hostname: engine-compiler
    volumes:
      - ./docker-deps/m2config:/root/.m2
      - ./docker-deps/libs:/root/.m2/repository/com/quicksand/bigdata
      - ../bdt-query-engine:/home/bdt-query-engine
    stdin_open: true
    tty: true
    working_dir:
      /home/bdt-query-engine
    entrypoint: [ "sh", "./compile-java.sh" ]
