version: '3'

services:

  bdt-query-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: bdt-query-engine:1.0
    container_name: bdt-query-engine
    hostname: bdt-query-engine
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 64M
    volumes:
      - /tmp:/tmp
    ports:
      - "9100:9100"
      - "9101:9101"
    networks:
      devnws:
        ipv4_address: 192.168.10.160

# docker network create --driver=bridge --subnet=192.168.10.0/24 --ip-range=192.168.10.0/24 --gateway=192.168.10.1 devnws
networks:
  devnws:
    external: true